# Site settings 
title: "Vasileios Boukonis Blog"
name: "Vasileios Boukonis"
baseurl: "/vbouk"
email: vasiliss_b@hotmail.com
twitter_username: vasilisdev
github_username:  va5ili5

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate : 10